# Generated by Django 4.0 on 2021-12-09 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Proje Adı')),
                ('lesson', models.CharField(max_length=50, verbose_name='Ders')),
                ('period', models.CharField(max_length=50, verbose_name='Dönem')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('key_words', models.CharField(max_length=50, verbose_name='Anahtar Kelimeler')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Yazar')),
            ],
        ),
    ]
