# Generated by Django 4.0 on 2021-12-10 19:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_remove_pdf_key_words_remove_pdf_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(upload_to='', verbose_name='PDF dosyası'),
        ),
    ]
