# Generated by Django 4.0 on 2021-12-10 20:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_alter_pdf_content_alter_pdf_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='İçerik'),
        ),
    ]
