# Generated by Django 4.0 on 2021-12-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_alter_pdf_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='content',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='İçerik'),
        ),
    ]
