# Generated by Django 4.0 on 2021-12-12 13:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0006_alter_pdf_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='İçerik'),
        ),
    ]
